name: C++ Lint

on:
  push:
  pull_request:
    branches: [ main, dev ]

env:
  CLANG_FORMAT_VERSION: 17

  home: /home/runner

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache clang-format dependency
        uses: actions/cache@v4
        id: clang-format-cache
        with:
          path: "${{ env.home }}/clang-format"
          key: "clang-format-${{ env.CLANG_FORMAT_VERSION }}"

      - name: Install dependencies
        env:
          VERSION: ${{ env.CLANG_FORMAT_VERSION }}
          CACHE_HIT: ${{ steps.clang-format-cache.outputs.cache-hit }}
          CACHE_PATH: ${{ env.home }}/clang-format
        run: |
          if [[ "${CACHE_HIT}" == 'true' ]]; then
            sudo cp --verbose --force --recursive ${CACHE_PATH}/* /
          else
            wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc > /dev/null
            sudo apt-add-repository -y "deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-${VERSION} main"
            sudo apt-get install -y clang-format-${VERSION}
          
            mkdir -p $CACHE_PATH

            sudo dpkg -L clang-format-${VERSION} | \
              while IFS= read -r f; do \
                if test -f $f; then \
                  echo $f; \
                fi; \
              done | \
              xargs cp --parents --target-directory ${CACHE_PATH}
          fi

      - name: Run clang-format
        run: |
          cd ${{ github.workspace }}
          find Engine examples -name '*.cpp' -or -name '*.h' -or -name '*.hpp' | xargs clang-format-${{ env.CLANG_FORMAT_VERSION }} -i -style=file

      - name: Check for differences
        run: |
          git diff --exit-code || (echo "Code is not formatted properly" && exit 1)
