name: C++ Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Run clang-format
      run: find . -name '*.cpp' -or -name '*.h' | xargs clang-format -i -style=Google

    - name: Check for differences
      run: |
        git diff --exit-code || (echo "Code is not formatted properly" && exit 1)
